[package]
name = "key_set"
version = "0.1.0"
authors = ["Eduardo Turiño <eturino@eturino.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
